return function ($context) {return $context->getAndWrap('exception');};